spring:
  application:
    name: notification-service

  profiles:
    active: dev

  config:
    import:
      - "optional:configserver:"
      - "classpath:shared/application-common.yml"
      - "classpath:shared/logging.yml"
      - "classpath:shared/messages.yml"
      - "classpath:shared/actuator.yml"

  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
