server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
        - TokenRelay
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:

        # ----------------------- AUTH SERVICE -----------------------
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # ----------------------- PRODUCT SERVICE -----------------------
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # ----------------------- INVENTORY SERVICE -----------------------
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # ----------------------- ORDER SERVICE -----------------------
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # ----------------------- PAYMENT SERVICE -----------------------
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # ----------------------- NOTIFICATION SERVICE -----------------------
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # ----------------------- AGGREGATION SERVICE -----------------------
        - id: aggregation-service
          uri: lb://aggregation-service
          predicates:
            - Path=/api/aggregate/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

# ----------------------- JWT CONFIG -----------------------
jwt:
  secret: ${JWT_SECRET:YgH9kLmN2sP5vX7qT0wA3cD6fG8jK1mR4uE7yB0nV2tQ5oS8xC3bW6zJ9pL1aF4}}
  expiration: 3600000

# ----------------------- RESILIENCE4J -----------------------
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
    instances:
      product-service:
        base-config: default
      order-service:
        base-config: default
      payment-service:
        base-config: default

# ----------------------- LOGGING -----------------------
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: INFO
