spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notify/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        - id: aggregation-service
          uri: lb://aggregation-service
          predicates:
            - Path=/api/aggregate/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

jwt:
  secret: ${JWT_SECRET:YgH9kLmN2sP5vX7qT0wA3cD6fG8jK1mR4uE7yB0nV2tQ5oS8xC3bW6zJ9pL1aF4}
  expiration: 3600000

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      order-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      payment-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: INFO
