spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:YgH9kLmN2sP5vX7qT0wA3cD6fG8jK1mR4uE7yB0nV2tQ5oS8xC3bW6zJ9pL1aF4}
  expiration: ${JWT_EXPIRATION:3600000}

logging:
  level:
    root: INFO
    com.ecommerce.auth: DEBUG
    org.springframework.security: DEBUG
