spring:
  application:
    name: payment-service

  profiles:
    active: dev

  config:
    import:
      - "optional:configserver:"
      - "classpath:shared/application-common.yml"
      - "classpath:shared/logging.yml"
      - "classpath:shared/messages.yml"
      - "classpath:shared/actuator.yml"

server:
  port: 0   # dynamic port for load balancing

management:
  endpoints:
    web:
      exposure:
        include: "*"
