spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payment_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

payment:
  provider: stripe
  currency: "INR"

  stripe:
    secret-key: ${STRIPE_SECRET_KEY:sk_test_dev_123}
    public-key: ${STRIPE_PUBLIC_KEY:pk_test_dev_123}

logging:
  level:
    root: INFO
    com.ecommerce.payment: DEBUG
