spring:
  application:
    name: gateway-service

  profiles:
    active: dev

  config:
    import:
      - "optional:configserver:"
      - "classpath:shared/application-common.yml"
      - "classpath:shared/logging.yml"
      - "classpath:shared/messages.yml"
      - "classpath:shared/actuator.yml"

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
