server:
  port: 80

spring:
  application:
    name: gateway-service

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 8s
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://yourcompany.com"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        failure-rate-threshold: 30
        wait-duration-in-open-state: 20s
      order-service:
        failure-rate-threshold: 30
        wait-duration-in-open-state: 20s
      payment-service:
        failure-rate-threshold: 30
        wait-duration-in-open-state: 20s

logging:
  level:
    root: WARN
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: WARN
