logging:
  level:
    root: INFO

    # Spring framework logs
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.cloud: INFO

    # Hibernate + SQL
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # Resilience4j
    io.github.resilience4j: INFO

    # Custom Business Logging
    com.ecommerce: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/application.log

# Enable color output
spring:
  output:
    ansi:
      enabled: ALWAYS
