spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/aggregation_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

services:
  product: http://api-gateway:9000/api/products
  inventory: http://api-gateway:9000/api/inventory
  order: http://api-gateway:9000/api/orders
  payment: http://api-gateway:9000/api/payments
  notification: http://api-gateway:9000/api/notify

logging:
  level:
    root: INFO
    com.ecommerce.aggregation: DEBUG
