server:
  port: 0

spring:
  application:
    name: aggregation-service

  profiles:
    active: dev

  config:
    import:
      - "optional:configserver:"
      - "classpath:shared/application-common.yml"
      - "classpath:shared/logging.yml"
      - "classpath:shared/messages.yml"
      - "classpath:shared/actuator.yml"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
